# Generated by Django 5.0.3 on 2024-03-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognews',
            name='file',
            field=models.FileField(null=True, upload_to='music'),
        ),
    ]
