# Generated by Django 5.0.3 on 2024-03-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blognews_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognews',
            name='file',
        ),
    ]
