# Generated by Django 5.0.3 on 2024-03-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blognews_image_blognews_music_blognews_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blognews',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
